[firebase]
api_key = "AIzaSy..."
auth_domain = "surplus-food-8cfab.firebaseapp.com"
project_id = "surplus-food-8cfab"
storage_bucket = "surplus-food-8cfab.appspot.com"
messaging_sender_id = "626699448528"
app_id = "1:626699448528:web:b7ad5ce262fcbf3c13aed5"
api_key = "AIzaSyD3lliAxIbOvgkpTS4MzBZplBv7c8Bx1VE" 